/mob/living/carbon/update_sight()
	if(mind)
		var/datum/antagonist/vampire/V = mind.has_antag_datum(/datum/antagonist/vampire)
		if(V)
			if(V.get_ability(/datum/vampire_passive/full))
				ADD_TRAIT(src, TRAIT_TRUE_NIGHT_VISION, "full_vamp")
				ADD_TRAIT(src, TRAIT_XRAY_VISION, "full_vamp")
			else if(V.get_ability(/datum/vampire_passive/vision))
				ADD_TRAIT(src, TRAIT_THERMAL_VISION, "partial_vamp")
	return ..()
